max-jobs-per-second: 10
default-resources:
    mem_mb: 2000
set-threads:
    search: 6
    refine: 4
set-resources:
    search:
        mem: 48000MB
    refine:
        mem: 64000MB
    aggregate:
        mem: 128000MB
